#!/bin/bash

DUMP=$1

cd ~/src/icisstaff

echo 'Killing database connections'
sudo pkill -SIGTERM -f icisstaff_development

echo 'Droping and recreating database'
bundle exec rake db:drop db:create

echo 'Restoring database with dump: '$DUMP
pg_restore -O -x -n public -d icisstaff_development $DUMP

echo 'Migrating database'
bundle exec rake db:migrate
